name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }] # daily at 00:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Gruntrexpewrus
          template: classic
          config_timezone: Asia/Tokyo
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_traffic: yes
